[package]
name = "synapse-application"
version = "0.1.0"
edition.workspace = true

[dependencies]
synapse-core = { path = "../synapse-core" }
async-trait = { workspace = true }
uuid = { workspace = true }
